# Generated by Django 5.0.2 on 2024-02-23 12:55

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Member',
            fields=[
                ('name', models.CharField(max_length=30, unique=True)),
                ('slack_id', models.CharField(max_length=10, primary_key=True, serialize=False)),
            ],
        ),
    ]
