# Generated by Django 5.0.2 on 2024-02-23 12:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('schedule', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='member',
            name='slack_id',
            field=models.CharField(max_length=20, primary_key=True, serialize=False),
        ),
    ]
