# Generated by Django 5.0.2 on 2024-02-23 14:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('schedule', '0002_alter_member_slack_id'),
    ]

    operations = [
        migrations.CreateModel(
            name='DateOption',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('participants', models.ManyToManyField(related_name='available_dates', to='schedule.member')),
            ],
        ),
    ]
