# Generated by Django 5.0.2 on 2024-02-24 17:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('schedule', '0003_dateoption'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dateoption',
            name='date',
            field=models.DateField(unique=True),
        ),
    ]
