# Generated by Django 5.0.2 on 2024-02-26 12:36

import django.db.models.deletion
import schedule.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('schedule', '0004_alter_dateoption_date'),
    ]

    operations = [
        migrations.CreateModel(
            name='ScheduleSession',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('description', models.TextField(blank=True, null=True)),
            ],
        ),
        migrations.AddField(
            model_name='dateoption',
            name='session',
            field=models.ForeignKey(default=schedule.models.get_default_session, on_delete=django.db.models.deletion.CASCADE, related_name='date_options', to='schedule.schedulesession'),
        ),
    ]
