# Generated by Django 5.0.2 on 2024-02-27 02:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('schedule', '0004_alter_dateoption_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='member',
            name='date_options',
            field=models.ManyToManyField(related_name='members', to='schedule.dateoption'),
        ),
    ]
