# Generated by Django 5.0.2 on 2024-02-27 09:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('schedule', '0005_member_date_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='dateoption',
            name='title',
            field=models.CharField(default='title', max_length=30, unique=True),
        ),
    ]
