# Generated by Django 5.0.2 on 2024-02-26 14:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('schedule', '0005_schedulesession_dateoption_session'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='dateoption',
            name='session',
        ),
        migrations.AddField(
            model_name='schedulesession',
            name='dates',
            field=models.ManyToManyField(related_name='sessions', to='schedule.dateoption'),
        ),
    ]
