# Generated by Django 5.0.2 on 2024-02-27 13:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('schedule', '0010_alter_dateoption_title'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dateoption',
            name='title',
            field=models.CharField(max_length=30),
        ),
    ]
