# Generated by Django 5.0.2 on 2024-03-06 16:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('schedule', '0011_alter_dateoption_title'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dateoption',
            name='title',
            field=models.CharField(max_length=30, unique=True),
        ),
    ]
