# Generated by Django 5.0.2 on 2024-03-06 17:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('schedule', '0012_alter_dateoption_title'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='dateoption',
            name='title',
        ),
    ]
