# Generated by Django 5.0.2 on 2024-03-06 18:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('schedule', '0013_remove_dateoption_title'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='member',
            name='date_options',
        ),
    ]
