# Generated by Django 5.0.2 on 2024-03-07 18:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('schedule', '0015_event_participant_delete_dateoption_delete_member'),
    ]

    operations = [
        migrations.RenameField(
            model_name='event',
            old_name='end_time',
            new_name='date',
        ),
        migrations.RemoveField(
            model_name='event',
            name='start_time',
        ),
    ]
