# Generated by Django 5.0.2 on 2024-03-08 12:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('schedule', '0016_alter_dateoption_participants'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dateoption',
            name='participants',
            field=models.ManyToManyField(related_name='available_dates', to='schedule.member'),
        ),
    ]
