# Generated by Django 5.0.2 on 2024-03-07 19:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('schedule', '0017_eventdate'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='event',
            name='date',
        ),
    ]
