# Generated by Django 5.0.2 on 2024-03-08 14:47

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('schedule', '0017_alter_dateoption_participants'),
    ]

    operations = [
        migrations.CreateModel(
            name='EventParticipant',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('event_date', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='event_participants', to='schedule.eventdate')),
                ('participant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='event_dates', to='schedule.member')),
            ],
        ),
    ]
